# docker-compose.yaml
version: '3.3'
services:
  backend:
    image: msgdevopscommunity/taschenrechner_backend:latest
    container_name: backend
    ports:
      - 8100:8100
  frontend:
    image: msgdevopscommunity/taschenrechner_frontend:latest
    container_name: frontend
    ports:
      - 85:80
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --interval 30 backend frontend

volumes:
  jenkins_home: