# This is a basic workflow that is manually triggered

name: Publish Containers and Deploy 
# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_and_publish_backend:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v3
        - name: Build the Docker image
          run: |
            docker login --username msgdevopscommunity --password dckr_pat_zs1mDHGFMrAw-nzScZmay-b1fnI
            docker build --file Backend_Dockerfile --tag msgdevopscommunity/taschenrechner_backend:latest --push .
  build_and_publish_frontend:
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: |
            docker login --username msgdevopscommunity --password dckr_pat_zs1mDHGFMrAw-nzScZmay-b1fnI
            docker image prune
            docker build --file Frontend_Dockerfile --tag msgdevopscommunity/taschenrechner_frontend:latest --push .
